In [1]:
import pandas as pd
from sklearn.preprocessing import StandardScaler,OneHotEncoder,LabelEncoder
from sklearn.model_selection import train_test_split
import pickle

In [3]:
## loading the data 
data = pd.read_csv('predictive_maintenance_dataset (1).csv')
data.head(20)

,timestamp,machine_id,vibration,acoustic,temperature,current,IMF_1,IMF_2,IMF_3,label
0,2024-07-01 08:00:00,M01,0.822,0.645,66.85,13.04,0.196,0.033,0.000,0
1,2024-07-01 08:01:00,M01,1.398,0.834,76.20,15.08,0.345,0.132,0.001,1
2,2024-07-01 08:02:00,M01,0.856,0.590,67.03,12.30,0.187,0.017,0.002,0
3,2024-07-01 08:03:00,M01,0.793,0.544,65.04,11.69,0.196,-0.060,0.003,0
4,2024-07-01 08:04:00,M01,1.279,0.721,78.19,14.84,0.330,-0.115,0.004,1
5,2024-07-01 08:05:00,M01,0.782,0.655,61.95,11.56,0.164,-0.081,0.005,0
6,2024-07-01 08:06:00,M01,0.837,0.564,64.52,10.98,0.238,-0.095,0.006,0
7,2024-07-01 08:07:00,M01,0.725,0.652,62.87,11.89,0.214,-0.076,0.007,0
8,2024-07-01 08:08:00,M01,0.803,0.702,64.51,11.19,0.145,-0.004,0.008,0
9,2024-07-01 08:09:00,M01,0.779,0.539,61.30,12.51,0.103,-0.025,0.009,0
10,2024-07-01 08:10:00,M01,0.897,0.627,67.18,11.18,0.093,0.097,0.010,0
11,2024-07-01 08:11:00,M01,0.789,0.603,65.80,11.27,0.086,-0.080,0.011,0
12,2024-07-01 08:12:00,M01,0.726,0.575,65.57,12.85,0.079,-0.022,0.012,0
13,2024-07-01 08:13:00,M01,0.826,0.485,66.41,12.15,0.156,-0.005,0.013,0
14,2024-07-01 08:14:00,M01,0.823,0.582,65.28,12.31,0.217,0.050,0.014,0
15,2024-07-01 08:15:00,M01,0.882,0.594,62.76,12.53,0.223,-0.059,0.015,0
16,2024-07-01 08:16:00,M01,0.783,0.631,64.99,12.56,0.164,-0.107,0.016,0
17,2024-07-01 08:17:00,M01,0.793,0.576,66.74,12.36,0.168,0.018,0.017,0
18,2024-07-01 08:18:00,M01,0.754,0.600,65.08,12.44,0.077,-0.073,0.018,0
19,2024-07-01 08:19:00,M01,0.917,0.630,65.19,11.82,0.243,0.124,0.019,0

In [4]:
## dropping the irrelevant data
data = data.drop(['timestamp','machine_id'], axis=1)
data.head()

   vibration  acoustic  temperature  current  IMF_1  IMF_2  IMF_3  label
0      0.822     0.645        66.85    13.04  0.196  0.033  0.000      0
1      1.398     0.834        76.20    15.08  0.345  0.132  0.001      1
2      0.856     0.590        67.03    12.30  0.187  0.017  0.002      0
3      0.793     0.544        65.04    11.69  0.196 -0.060  0.003      0
4      1.279     0.721        78.19    14.84  0.330 -0.115  0.004      1

In [5]:
## now dividing the data into independant and dependant feature
X = data.drop('label', axis=1)
y = data['label']

## now seprate the data for train and test split
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.2, random_state=42 )

## now scaling the data 
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [7]:
X_test

array([[-0.24264252, -0.51644648, -0.14582408, ..., -0.29821738,
        -1.41545947,  1.37375188],
       [-0.55887962, -1.05511833, -0.03190847, ..., -1.22679843,
         0.07563831,  0.73126967],
       [ 0.26480772,  0.23583662, -0.81591592, ..., -1.24465576,
         0.4346063 , -1.11237491],
       ...,
       [ 0.02211413,  0.1893994 , -0.1748614 , ...,  0.59464902,
         1.6357684 , -1.36378099],
       [ 0.02946848, -0.75792006,  0.02616616, ..., -1.45894369,
        -0.82178165,  1.34581787],
       [-0.30883168, -0.3585599 ,  0.03286707, ..., -0.24464539,
        -0.73894288,  1.37375188]])

In [8]:
## now creating pickle file for scalar so any value comes we first scale that value
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler, file)

In [9]:
data

      vibration  acoustic  temperature  current  IMF_1  IMF_2  IMF_3  label
0         0.822     0.645        66.85    13.04  0.196  0.033  0.000      0
1         1.398     0.834        76.20    15.08  0.345  0.132  0.001      1
2         0.856     0.590        67.03    12.30  0.187  0.017  0.002      0
3         0.793     0.544        65.04    11.69  0.196 -0.060  0.003      0
4         1.279     0.721        78.19    14.84  0.330 -0.115  0.004      1
...         ...       ...          ...      ...    ...    ...    ...    ...
1795      1.163     0.889        78.43    14.41  0.261  0.041 -0.031      1
1796      0.838     0.545        64.28    12.08  0.146 -0.062 -0.030      0
1797      0.786     0.593        65.44    12.23  0.110  0.038 -0.029      0
1798      0.767     0.550        62.01    11.35  0.225  0.106 -0.028      0
1799      0.934     0.643        64.18    11.83  0.122  0.015 -0.028      0

[1800 rows x 8 columns]

In [11]:
### ANN implementation
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [13]:
## lets build our ANN model
model = Sequential([

Dense(64, activation='relu', input_shape = (X_train.shape[1],)),
Dense(32, activation='relu'),
Dense(1, activation='sigmoid')




]



)

In [14]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 64)                512

 dense_4 (Dense)             (None, 32)                2080

 dense_5 (Dense)             (None, 1)                 33

=================================================================
Total params: 2625 (10.25 KB)
Trainable params: 2625 (10.25 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [16]:
## compiling the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [18]:
from tensorflow.keras.callbacks import EarlyStopping

early_stooping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [19]:
## now lets train the model
history = model.fit(
    X_train,y_train, validation_data=(X_test,y_test), epochs = 100,
    callbacks = [early_stooping_callback]
)

Epoch 1/100
WARNING:tensorflow:From c:\Users\Ayan\Desktop\ANN_Project_2\venv\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From c:\Users\Ayan\Desktop\ANN_Project_2\venv\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

45/45 [==============================] - 1s 4ms/step - loss: 0.3501 - accuracy: 0.9715 - val_loss: 0.1229 - val_accuracy: 1.0000
Epoch 2/100
45/45 [==============================] - 0s 2ms/step - loss: 0.0600 - accuracy: 1.0000 - val_loss: 0.0229 - val_accuracy: 1.0000
Epoch 3/100
45/45 [==============================] - 0s 1ms/step - loss: 0.0158 - accuracy: 1.0000 - val_loss: 0.0094 - val_accuracy: 1.0000
Epoch 4/100
45/45 [==============================] - 0s 1ms/step - loss: 0.0077 - accuracy: 1.0000 - val_loss: 0.0052 - val_accuracy: 1.0000
Epoch 5/100
45/45 [==============================] - 0s 1ms/step - loss: 0.0047 - accuracy: 1.0000 - val_loss: 0.0034 - val_accuracy: 1.0000
Epoch 6/100
45/45 [==============================] - 0s 1ms/step - loss: 0.0032 - accuracy: 1.0000 - val_loss: 0.0024 - val_accuracy: 1.0000
Epoch 7/100
45/45 [==============================] - 0s 1ms/step - loss: 0.0024 - accuracy: 1.0000 - val_loss: 0.0018 - val_accuracy: 1.0000
Epoch 8/100
45/45 [==============================] - 0s 1ms/step - loss: 0.0018 - accuracy: 1.0000 - val_loss: 0.0014 - val_accuracy: 1.0000
Epoch 9/100
45/45 [==============================] - 0s 1ms/step - loss: 0.0015 - accuracy: 1.0000 - val_loss: 0.0011 - val_accuracy: 1.0000
Epoch 10/100
45/45 [==============================] - 0s 1ms/step - loss: 0.0012 - accuracy: 1.0000 - val_loss: 9.1641e-04 - val_accuracy: 1.0000
Epoch 11/100
45/45 [==============================] - 0s 1ms/step - loss: 0.0010 - accuracy: 1.0000 - val_loss: 7.5937e-04 - val_accuracy: 1.0000
Epoch 12/100
45/45 [==============================] - 0s 1ms/step - loss: 8.3946e-04 - accuracy: 1.0000 - val_loss: 6.4862e-04 - val_accuracy: 1.0000
Epoch 13/100
45/45 [==============================] - 0s 1ms/step - loss: 7.2104e-04 - accuracy: 1.0000 - val_loss: 5.5565e-04 - val_accuracy: 1.0000
Epoch 14/100
45/45 [==============================] - 0s 1ms/step - loss: 6.2838e-04 - accuracy: 1.0000 - val_loss: 4.8059e-04 - val_accuracy: 1.0000
Epoch 15/100
45/45 [==============================] - 0s 1ms/step - loss: 5.4693e-04 - accuracy: 1.0000 - val_loss: 4.2281e-04 - val_accuracy: 1.0000
Epoch 16/100
45/45 [==============================] - 0s 1ms/step - loss: 4.8194e-04 - accuracy: 1.0000 - val_loss: 3.7173e-04 - val_accuracy: 1.0000
Epoch 17/100
45/45 [==============================] - 0s 1ms/step - loss: 4.2699e-04 - accuracy: 1.0000 - val_loss: 3.3121e-04 - val_accuracy: 1.0000
Epoch 18/100
45/45 [==============================] - 0s 1ms/step - loss: 3.8163e-04 - accuracy: 1.0000 - val_loss: 2.9574e-04 - val_accuracy: 1.0000
Epoch 19/100
45/45 [==============================] - 0s 1ms/step - loss: 3.4165e-04 - accuracy: 1.0000 - val_loss: 2.6832e-04 - val_accuracy: 1.0000
Epoch 20/100
45/45 [==============================] - 0s 1ms/step - loss: 3.0971e-04 - accuracy: 1.0000 - val_loss: 2.4046e-04 - val_accuracy: 1.0000
Epoch 21/100
45/45 [==============================] - 0s 1ms/step - loss: 2.7969e-04 - accuracy: 1.0000 - val_loss: 2.1942e-04 - val_accuracy: 1.0000
Epoch 22/100
45/45 [==============================] - 0s 1ms/step - loss: 2.5446e-04 - accuracy: 1.0000 - val_loss: 1.9975e-04 - val_accuracy: 1.0000
Epoch 23/100
45/45 [==============================] - 0s 1ms/step - loss: 2.3271e-04 - accuracy: 1.0000 - val_loss: 1.8252e-04 - val_accuracy: 1.0000
Epoch 24/100
45/45 [==============================] - 0s 1ms/step - loss: 2.1290e-04 - accuracy: 1.0000 - val_loss: 1.6792e-04 - val_accuracy: 1.0000
Epoch 25/100
45/45 [==============================] - 0s 1ms/step - loss: 1.9599e-04 - accuracy: 1.0000 - val_loss: 1.5465e-04 - val_accuracy: 1.0000
Epoch 26/100
45/45 [==============================] - 0s 1ms/step - loss: 1.8050e-04 - accuracy: 1.0000 - val_loss: 1.4325e-04 - val_accuracy: 1.0000
Epoch 27/100
45/45 [==============================] - 0s 1ms/step - loss: 1.6724e-04 - accuracy: 1.0000 - val_loss: 1.3317e-04 - val_accuracy: 1.0000
Epoch 28/100
45/45 [==============================] - 0s 1ms/step - loss: 1.5520e-04 - accuracy: 1.0000 - val_loss: 1.2423e-04 - val_accuracy: 1.0000
Epoch 29/100
45/45 [==============================] - 0s 1ms/step - loss: 1.4385e-04 - accuracy: 1.0000 - val_loss: 1.1525e-04 - val_accuracy: 1.0000
Epoch 30/100
45/45 [==============================] - 0s 1ms/step - loss: 1.3337e-04 - accuracy: 1.0000 - val_loss: 1.0747e-04 - val_accuracy: 1.0000
Epoch 31/100
45/45 [==============================] - 0s 1ms/step - loss: 1.2441e-04 - accuracy: 1.0000 - val_loss: 1.0063e-04 - val_accuracy: 1.0000
Epoch 32/100
45/45 [==============================] - 0s 1ms/step - loss: 1.1652e-04 - accuracy: 1.0000 - val_loss: 9.4009e-05 - val_accuracy: 1.0000
Epoch 33/100
45/45 [==============================] - 0s 1ms/step - loss: 1.0886e-04 - accuracy: 1.0000 - val_loss: 8.8394e-05 - val_accuracy: 1.0000
Epoch 34/100
45/45 [==============================] - 0s 1ms/step - loss: 1.0194e-04 - accuracy: 1.0000 - val_loss: 8.2777e-05 - val_accuracy: 1.0000
Epoch 35/100
45/45 [==============================] - 0s 1ms/step - loss: 9.5524e-05 - accuracy: 1.0000 - val_loss: 7.8267e-05 - val_accuracy: 1.0000
Epoch 36/100
45/45 [==============================] - 0s 1ms/step - loss: 8.9989e-05 - accuracy: 1.0000 - val_loss: 7.3528e-05 - val_accuracy: 1.0000
Epoch 37/100
45/45 [==============================] - 0s 1ms/step - loss: 8.4813e-05 - accuracy: 1.0000 - val_loss: 6.9470e-05 - val_accuracy: 1.0000
Epoch 38/100
45/45 [==============================] - 0s 1ms/step - loss: 7.9684e-05 - accuracy: 1.0000 - val_loss: 6.5872e-05 - val_accuracy: 1.0000
Epoch 39/100
45/45 [==============================] - 0s 1ms/step - loss: 7.5431e-05 - accuracy: 1.0000 - val_loss: 6.2089e-05 - val_accuracy: 1.0000
Epoch 40/100
45/45 [==============================] - 0s 2ms/step - loss: 7.0980e-05 - accuracy: 1.0000 - val_loss: 5.8927e-05 - val_accuracy: 1.0000
Epoch 41/100
45/45 [==============================] - 0s 1ms/step - loss: 6.7401e-05 - accuracy: 1.0000 - val_loss: 5.5874e-05 - val_accuracy: 1.0000
Epoch 42/100
45/45 [==============================] - 0s 1ms/step - loss: 6.3744e-05 - accuracy: 1.0000 - val_loss: 5.3064e-05 - val_accuracy: 1.0000
Epoch 43/100
45/45 [==============================] - 0s 1ms/step - loss: 6.0312e-05 - accuracy: 1.0000 - val_loss: 5.0760e-05 - val_accuracy: 1.0000
Epoch 44/100
45/45 [==============================] - 0s 1ms/step - loss: 5.7213e-05 - accuracy: 1.0000 - val_loss: 4.8200e-05 - val_accuracy: 1.0000
Epoch 45/100
45/45 [==============================] - 0s 1ms/step - loss: 5.4167e-05 - accuracy: 1.0000 - val_loss: 4.6086e-05 - val_accuracy: 1.0000
Epoch 46/100
45/45 [==============================] - 0s 1ms/step - loss: 5.1597e-05 - accuracy: 1.0000 - val_loss: 4.3672e-05 - val_accuracy: 1.0000
Epoch 47/100
45/45 [==============================] - 0s 1ms/step - loss: 4.8988e-05 - accuracy: 1.0000 - val_loss: 4.1673e-05 - val_accuracy: 1.0000
Epoch 48/100
45/45 [==============================] - 0s 1ms/step - loss: 4.6629e-05 - accuracy: 1.0000 - val_loss: 3.9761e-05 - val_accuracy: 1.0000
Epoch 49/100
45/45 [==============================] - 0s 1ms/step - loss: 4.4366e-05 - accuracy: 1.0000 - val_loss: 3.8212e-05 - val_accuracy: 1.0000
Epoch 50/100
45/45 [==============================] - 0s 1ms/step - loss: 4.2343e-05 - accuracy: 1.0000 - val_loss: 3.6384e-05 - val_accuracy: 1.0000
Epoch 51/100
45/45 [==============================] - 0s 1ms/step - loss: 4.0356e-05 - accuracy: 1.0000 - val_loss: 3.4872e-05 - val_accuracy: 1.0000
Epoch 52/100
45/45 [==============================] - 0s 1ms/step - loss: 3.8584e-05 - accuracy: 1.0000 - val_loss: 3.3386e-05 - val_accuracy: 1.0000
Epoch 53/100
45/45 [==============================] - 0s 1ms/step - loss: 3.6828e-05 - accuracy: 1.0000 - val_loss: 3.2061e-05 - val_accuracy: 1.0000
Epoch 54/100
45/45 [==============================] - 0s 1ms/step - loss: 3.5137e-05 - accuracy: 1.0000 - val_loss: 3.0727e-05 - val_accuracy: 1.0000
Epoch 55/100
45/45 [==============================] - 0s 1ms/step - loss: 3.3619e-05 - accuracy: 1.0000 - val_loss: 2.9485e-05 - val_accuracy: 1.0000
Epoch 56/100
45/45 [==============================] - 0s 1ms/step - loss: 3.2071e-05 - accuracy: 1.0000 - val_loss: 2.8327e-05 - val_accuracy: 1.0000
Epoch 57/100
45/45 [==============================] - 0s 1ms/step - loss: 3.0765e-05 - accuracy: 1.0000 - val_loss: 2.7272e-05 - val_accuracy: 1.0000
Epoch 58/100
45/45 [==============================] - 0s 1ms/step - loss: 2.9465e-05 - accuracy: 1.0000 - val_loss: 2.6208e-05 - val_accuracy: 1.0000
Epoch 59/100
45/45 [==============================] - 0s 1ms/step - loss: 2.8262e-05 - accuracy: 1.0000 - val_loss: 2.5154e-05 - val_accuracy: 1.0000
Epoch 60/100
45/45 [==============================] - 0s 1ms/step - loss: 2.7099e-05 - accuracy: 1.0000 - val_loss: 2.4191e-05 - val_accuracy: 1.0000
Epoch 61/100
45/45 [==============================] - 0s 1ms/step - loss: 2.5888e-05 - accuracy: 1.0000 - val_loss: 2.3255e-05 - val_accuracy: 1.0000
Epoch 62/100
45/45 [==============================] - 0s 1ms/step - loss: 2.4862e-05 - accuracy: 1.0000 - val_loss: 2.2435e-05 - val_accuracy: 1.0000
Epoch 63/100
45/45 [==============================] - 0s 1ms/step - loss: 2.3889e-05 - accuracy: 1.0000 - val_loss: 2.1658e-05 - val_accuracy: 1.0000
Epoch 64/100
45/45 [==============================] - 0s 1ms/step - loss: 2.2892e-05 - accuracy: 1.0000 - val_loss: 2.0879e-05 - val_accuracy: 1.0000
Epoch 65/100
45/45 [==============================] - 0s 1ms/step - loss: 2.2009e-05 - accuracy: 1.0000 - val_loss: 2.0124e-05 - val_accuracy: 1.0000
Epoch 66/100
45/45 [==============================] - 0s 1ms/step - loss: 2.1232e-05 - accuracy: 1.0000 - val_loss: 1.9321e-05 - val_accuracy: 1.0000
Epoch 67/100
45/45 [==============================] - 0s 1ms/step - loss: 2.0334e-05 - accuracy: 1.0000 - val_loss: 1.8709e-05 - val_accuracy: 1.0000
Epoch 68/100
45/45 [==============================] - 0s 1ms/step - loss: 1.9527e-05 - accuracy: 1.0000 - val_loss: 1.8055e-05 - val_accuracy: 1.0000
Epoch 69/100
45/45 [==============================] - 0s 1ms/step - loss: 1.8769e-05 - accuracy: 1.0000 - val_loss: 1.7469e-05 - val_accuracy: 1.0000
Epoch 70/100
45/45 [==============================] - 0s 1ms/step - loss: 1.8068e-05 - accuracy: 1.0000 - val_loss: 1.6846e-05 - val_accuracy: 1.0000
Epoch 71/100
45/45 [==============================] - 0s 1ms/step - loss: 1.7413e-05 - accuracy: 1.0000 - val_loss: 1.6319e-05 - val_accuracy: 1.0000
Epoch 72/100
45/45 [==============================] - 0s 1ms/step - loss: 1.6759e-05 - accuracy: 1.0000 - val_loss: 1.5724e-05 - val_accuracy: 1.0000
Epoch 73/100
45/45 [==============================] - 0s 2ms/step - loss: 1.6167e-05 - accuracy: 1.0000 - val_loss: 1.5174e-05 - val_accuracy: 1.0000
Epoch 74/100
45/45 [==============================] - 0s 1ms/step - loss: 1.5539e-05 - accuracy: 1.0000 - val_loss: 1.4724e-05 - val_accuracy: 1.0000
Epoch 75/100
45/45 [==============================] - 0s 1ms/step - loss: 1.4957e-05 - accuracy: 1.0000 - val_loss: 1.4319e-05 - val_accuracy: 1.0000
Epoch 76/100
45/45 [==============================] - 0s 1ms/step - loss: 1.4499e-05 - accuracy: 1.0000 - val_loss: 1.3781e-05 - val_accuracy: 1.0000
Epoch 77/100
45/45 [==============================] - 0s 1ms/step - loss: 1.3889e-05 - accuracy: 1.0000 - val_loss: 1.3373e-05 - val_accuracy: 1.0000
Epoch 78/100
45/45 [==============================] - 0s 1ms/step - loss: 1.3439e-05 - accuracy: 1.0000 - val_loss: 1.2911e-05 - val_accuracy: 1.0000
Epoch 79/100
45/45 [==============================] - 0s 1ms/step - loss: 1.2990e-05 - accuracy: 1.0000 - val_loss: 1.2521e-05 - val_accuracy: 1.0000
Epoch 80/100
45/45 [==============================] - 0s 1ms/step - loss: 1.2491e-05 - accuracy: 1.0000 - val_loss: 1.2128e-05 - val_accuracy: 1.0000
Epoch 81/100
45/45 [==============================] - 0s 1ms/step - loss: 1.2057e-05 - accuracy: 1.0000 - val_loss: 1.1739e-05 - val_accuracy: 1.0000
Epoch 82/100
45/45 [==============================] - 0s 1ms/step - loss: 1.1622e-05 - accuracy: 1.0000 - val_loss: 1.1400e-05 - val_accuracy: 1.0000
Epoch 83/100
45/45 [==============================] - 0s 1ms/step - loss: 1.1218e-05 - accuracy: 1.0000 - val_loss: 1.1044e-05 - val_accuracy: 1.0000
Epoch 84/100
45/45 [==============================] - 0s 1ms/step - loss: 1.0839e-05 - accuracy: 1.0000 - val_loss: 1.0699e-05 - val_accuracy: 1.0000
Epoch 85/100
45/45 [==============================] - 0s 1ms/step - loss: 1.0463e-05 - accuracy: 1.0000 - val_loss: 1.0407e-05 - val_accuracy: 1.0000
Epoch 86/100
45/45 [==============================] - 0s 1ms/step - loss: 1.0131e-05 - accuracy: 1.0000 - val_loss: 1.0031e-05 - val_accuracy: 1.0000
Epoch 87/100
45/45 [==============================] - 0s 1ms/step - loss: 9.7874e-06 - accuracy: 1.0000 - val_loss: 9.7557e-06 - val_accuracy: 1.0000
Epoch 88/100
45/45 [==============================] - 0s 1ms/step - loss: 9.4594e-06 - accuracy: 1.0000 - val_loss: 9.5040e-06 - val_accuracy: 1.0000
Epoch 89/100
45/45 [==============================] - 0s 1ms/step - loss: 9.1370e-06 - accuracy: 1.0000 - val_loss: 9.1884e-06 - val_accuracy: 1.0000
Epoch 90/100
45/45 [==============================] - 0s 1ms/step - loss: 8.8513e-06 - accuracy: 1.0000 - val_loss: 8.9120e-06 - val_accuracy: 1.0000
Epoch 91/100
45/45 [==============================] - 0s 1ms/step - loss: 8.5365e-06 - accuracy: 1.0000 - val_loss: 8.6827e-06 - val_accuracy: 1.0000
Epoch 92/100
45/45 [==============================] - 0s 1ms/step - loss: 8.2669e-06 - accuracy: 1.0000 - val_loss: 8.4103e-06 - val_accuracy: 1.0000
Epoch 93/100
45/45 [==============================] - 0s 1ms/step - loss: 7.9961e-06 - accuracy: 1.0000 - val_loss: 8.1667e-06 - val_accuracy: 1.0000
Epoch 94/100
45/45 [==============================] - 0s 1ms/step - loss: 7.7368e-06 - accuracy: 1.0000 - val_loss: 7.9623e-06 - val_accuracy: 1.0000
Epoch 95/100
45/45 [==============================] - 0s 1ms/step - loss: 7.4848e-06 - accuracy: 1.0000 - val_loss: 7.7265e-06 - val_accuracy: 1.0000
Epoch 96/100
45/45 [==============================] - 0s 1ms/step - loss: 7.2372e-06 - accuracy: 1.0000 - val_loss: 7.4991e-06 - val_accuracy: 1.0000
Epoch 97/100
45/45 [==============================] - 0s 1ms/step - loss: 7.0069e-06 - accuracy: 1.0000 - val_loss: 7.2825e-06 - val_accuracy: 1.0000
Epoch 98/100
45/45 [==============================] - 0s 1ms/step - loss: 6.7844e-06 - accuracy: 1.0000 - val_loss: 7.0833e-06 - val_accuracy: 1.0000
Epoch 99/100
45/45 [==============================] - 0s 1ms/step - loss: 6.5623e-06 - accuracy: 1.0000 - val_loss: 6.9068e-06 - val_accuracy: 1.0000
Epoch 100/100
45/45 [==============================] - 0s 1ms/step - loss: 6.3755e-06 - accuracy: 1.0000 - val_loss: 6.7228e-06 - val_accuracy: 1.0000

In [20]:
print(data['label'].value_counts())

label
0    1598
1     202
Name: count, dtype: int64

In [21]:
print("Train:")
print(y_train.value_counts())

print("\nTest:")
print(y_test.value_counts())

Train:
label
0    1279
1     161
Name: count, dtype: int64

Test:
label
0    319
1     41
Name: count, dtype: int64

In [22]:
from sklearn.metrics import classification_report, confusion_matrix

y_pred_prob = model.predict(X_test)
y_pred = (y_pred_prob > 0.5).astype(int)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

12/12 [==============================] - 0s 752us/step
[[319   0]
 [  0  41]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       319
           1       1.00      1.00      1.00        41

    accuracy                           1.00       360
   macro avg       1.00      1.00      1.00       360
weighted avg       1.00      1.00      1.00       360

In [24]:
print(data.groupby('label').mean(numeric_only=True))

       vibration  acoustic  temperature    current     IMF_1     IMF_2  \
label
0       0.798652  0.600558    64.959819  11.989587  0.160327 -0.000345
1       1.196460  0.897644    77.398564  15.010495  0.235272  0.003371

          IMF_3
label
0      0.000986
1     -0.001797

In [26]:
## save the model
model.save('model.h5')

c:\Users\Ayan\Desktop\ANN_Project_2\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(